[profile.default]
solc           = "0.8.19"
bytecode_hash  = "none"
optimizer_runs = 1_000_000
remappings     = ["@openzeppelin/=lib/openzeppelin-contracts/contracts/", "v3-core/=lib/v3-core"]
match_path     = "test/unit/*.sol"
verbosity      = 3
ignored_error_codes = []
fs_permissions = [
    { access = "write", path = "./scripts/optimized-deployer-meta" },
    { access = "write", path = "./scripts/unoptimized-deployer-meta" },
    { access = "read", path = "./out" },
    { access = "read", path = "./lib" },
]

[profile.ci.fuzz]
runs = 10_000

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000
