[profile.default]
solc           = "0.8.19"
bytecode_hash  = "ipfs"
optimizer_runs = 1_000_000
libs = ['lib']
remappings     = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "amm-core/=lib/amm-core",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]
match_path     = "test/unit/*.sol"
verbosity      = 3
ignored_error_codes = []
fs_permissions = [
    { access = "write", path = "./script/optimized-deployer-meta" },
    { access = "write", path = "./script/unoptimized-deployer-meta" },
    { access = "read", path = "./out" },
    { access = "read", path = "./lib" },
]

[profile.ci.fuzz]
runs = 10_000

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"

[profile.script]
optimizer_runs = 1_000_000
